[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
build_flags = 
    -DMQTT_MAX_PACKET_SIZE=512
lib_deps = 
    miguelbalboa/MFRC522
    marcoschwartz/LiquidCrystal_I2C
    knolleary/PubSubClient
